// Pokémon species name dictionary for the name pass.
//
// This is intentionally NOT a complete Pokédex — we only need the
// names that show up on listings the parser is likely to see.
// Coverage priority:
//   - All 151 Gen-1 starters + Eeveelutions (vintage staple).
//   - Iconic Gen-2/3 (Lugia, Ho-oh, Rayquaza, Mew/Mewtwo lines, etc.).
//   - Modern SV-era featured species (Koraidon, Miraidon, Iono,
//     Raging Bolt, Iron Crown, Pecharunt, Terapagos, Ogerpon, Fezandipiti).
//   - SWSH-era featured species (Zacian, Zamazenta, Eternatus, Calyrex
//     forms, Galarian birds).
//   - High-value chase species (Charizard, Pikachu, Mew, Rayquaza,
//     Umbreon, Sylveon, Eevee, Greninja, Gardevoir, etc.).
//
// The list is stored as an array (ordered) so iteration is
// deterministic for tests; the longest-match-wins logic in `name.ts`
// handles overlap (e.g. "mr. mime" before "mime").

export const POKEMON_NAME_DICT: readonly string[] = [
  // Gen 1 — the high-value subset that dominates eBay
  'charizard',
  'blastoise',
  'venusaur',
  'pikachu',
  'raichu',
  'mew',
  'mewtwo',
  'dragonair',
  'dragonite',
  'gyarados',
  'lapras',
  'snorlax',
  'eevee',
  'vaporeon',
  'jolteon',
  'flareon',
  'gengar',
  'haunter',
  'gastly',
  'alakazam',
  'machamp',
  'arcanine',
  'ninetales',
  'magneton',
  'zapdos',
  'moltres',
  'articuno',
  'bulbasaur',
  'ivysaur',
  'charmander',
  'charmeleon',
  'squirtle',
  'wartortle',
  'caterpie',
  'metapod',
  'butterfree',
  'weedle',
  'beedrill',
  'pidgey',
  'pidgeot',
  'rattata',
  'raticate',
  'spearow',
  'fearow',
  'ekans',
  'arbok',
  'sandshrew',
  'sandslash',
  'nidoran',
  'nidorina',
  'nidoqueen',
  'nidorino',
  'nidoking',
  'clefairy',
  'clefable',
  'vulpix',
  'jigglypuff',
  'wigglytuff',
  'zubat',
  'golbat',
  'oddish',
  'gloom',
  'vileplume',
  'paras',
  'parasect',
  'venonat',
  'venomoth',
  'diglett',
  'dugtrio',
  'meowth',
  'persian',
  'psyduck',
  'golduck',
  'mankey',
  'primeape',
  'growlithe',
  'poliwag',
  'poliwhirl',
  'poliwrath',
  'abra',
  'kadabra',
  'machop',
  'machoke',
  'bellsprout',
  'weepinbell',
  'victreebel',
  'tentacool',
  'tentacruel',
  'geodude',
  'graveler',
  'golem',
  'ponyta',
  'rapidash',
  'slowpoke',
  'slowbro',
  'magnemite',
  'farfetchd',
  'doduo',
  'dodrio',
  'seel',
  'dewgong',
  'grimer',
  'muk',
  'shellder',
  'cloyster',
  'onix',
  'drowzee',
  'hypno',
  'krabby',
  'kingler',
  'voltorb',
  'electrode',
  'exeggcute',
  'exeggutor',
  'cubone',
  'marowak',
  'hitmonlee',
  'hitmonchan',
  'lickitung',
  'koffing',
  'weezing',
  'rhyhorn',
  'rhydon',
  'chansey',
  'tangela',
  'kangaskhan',
  'horsea',
  'seadra',
  'goldeen',
  'seaking',
  'staryu',
  'starmie',
  'mr. mime',
  'mr mime',
  'scyther',
  'jynx',
  'electabuzz',
  'magmar',
  'pinsir',
  'tauros',
  'magikarp',
  'ditto',
  'porygon',
  'omanyte',
  'omastar',
  'kabuto',
  'kabutops',
  'aerodactyl',
  // Gen 2 — Eeveelutions + iconic
  'espeon',
  'umbreon',
  'lugia',
  'ho-oh',
  'hooh',
  'celebi',
  'tyranitar',
  'feraligatr',
  'meganium',
  'typhlosion',
  'ampharos',
  'kingdra',
  'scizor',
  'heracross',
  'donphan',
  'suicune',
  'raikou',
  'entei',
  // Gen 3
  'rayquaza',
  'kyogre',
  'groudon',
  'jirachi',
  'deoxys',
  'gardevoir',
  'salamence',
  'metagross',
  'flygon',
  'absol',
  'latios',
  'latias',
  'aggron',
  // Gen 4
  'leafeon',
  'glaceon',
  'lucario',
  'garchomp',
  'gallade',
  'darkrai',
  'arceus',
  'giratina',
  'palkia',
  'dialga',
  'shaymin',
  // Gen 5
  'reshiram',
  'zekrom',
  'kyurem',
  'genesect',
  'meloetta',
  'keldeo',
  'victini',
  // Gen 6
  'sylveon',
  'greninja',
  'xerneas',
  'yveltal',
  'zygarde',
  'hoopa',
  'volcanion',
  // Gen 7
  'lunala',
  'solgaleo',
  'tapu koko',
  'tapu lele',
  'tapu bulu',
  'tapu fini',
  'necrozma',
  'magearna',
  'marshadow',
  'zeraora',
  'meltan',
  'melmetal',
  'incineroar',
  'decidueye',
  'primarina',
  // Gen 8
  'zacian',
  'zamazenta',
  'eternatus',
  'urshifu',
  'calyrex',
  'glastrier',
  'spectrier',
  'rillaboom',
  'cinderace',
  'inteleon',
  'dragapult',
  // Gen 9
  'koraidon',
  'miraidon',
  'meowscarada',
  'skeledirge',
  'quaquaval',
  'iono',
  'roaring moon',
  'iron valiant',
  'iron crown',
  'raging bolt',
  'gholdengo',
  'pecharunt',
  'terapagos',
  'ogerpon',
  'fezandipiti',
  'munkidori',
  'okidogi',
];
