/// <reference types="expo/types" />

// Auto-generated by Expo; manually committed because we don't
// run `expo prebuild` in CI. Re-generate via the `expo` CLI if
// the SDK upgrade introduces new typed env globals.
